__all__ = ['Sound', 'Svg']

from collections.abc import Sequence
from datetime import timedelta
from pathlib import Path
from typing import Self

import numpy as np
import numpy.typing as npt

class Sound[S: np.number]:
    def __init__(self, data: npt.NDArray[S], rate: int = ...) -> None: ...
    @property
    def channels(self) -> int: ...
    @property
    def duration(self) -> timedelta: ...
    def __array__(self) -> npt.NDArray[S]: ...
    def play(self, blocksize: int = ...) -> None: ...
    @classmethod
    def load(cls, path: Path | str) -> Self: ...
    def save(self, path: Path | str) -> None: ...

class Svg:
    def __init__(self, mask: np.ndarray, labels: Sequence[str]) -> None: ...
    def save(self, path: Path) -> None: ...
    @staticmethod
    def load(path: Path) -> dict[str, list[np.ndarray]]: ...
