from collections.abc import Callable, Iterator, KeysView
from typing import Any

class _Env:
    def keys(self) -> KeysView[str]: ...
    def __call__(self, **items: Any) -> _EnvCtx: ...
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> Any: ...
    def __eq__(self, rhs: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...

class _EnvCtx:
    def __call__[**P, R](self, fn: Callable[P, R]) -> Callable[P, R]: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *_) -> None: ...

env: _Env
